[package]
name = "stringed"
version = "0.1.0"
authors = ["neverRare"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stringed_core = { path = "../core" }
